/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Get an additional Action': '',
    'Heroes': '英雄',
    'Import save': '导入存档',
    'Export save': '导出存档',
    'Infinity': '无限',
    'Quality': '优质',
    'HP': '生命值',
    ', you found the following heroes': '，您发现以下英雄',
    'Bars': '金属条',
    'Active': '激活',
    'Advanced': '高级',
    'Basic': '基础',
    'Boards': '板子',
    'Beams': '横梁',
    'Bought': '已购买',
    'Buy max (M': '最买最大 (M',
    'Buy max (T': '最买最大 (T',
    'Changelog': '更新日志',
    'Close': '关闭',
    'Common': '常见的',
    'Cost': '成本',
    'Dimension': '维度',
    'Dimensions': '维度',
    'Default': '默认',
    'Final': '顶级',
    'Gems': '宝石',
    'Galaxy': '星系',
    'Infinity Points': '无限点',
    'Actions': '操作',
    'Actions left': '剩下的操作',
    'Automation': '自动化',
    'Control': '控制',
    'Continue': '继续',
    'Level': '等级',
    'Need': '需要',
    'Notation': '符号',
    'Nyan Cat': '彩虹猫',
    'Points': '点数',
    'Point': '点数',
    'Proceed': '继续进行',
    'Regular': '常规',
    'Unlock': '解锁',
    'Usain Bolt': '尤塞恩·博尔特',
    'Tickspeed Upgrades': 'Tick速度升级',
    'Tickspeed': 'Tick速度',
    'Towers': '塔',
    'Ships': '船',
    'Show newsticker': '显示新贴纸',
    'Roads': '道路',
    'Rocks': '石头',
    'Rods': '鱼竿',
    'Slowpoke': '慢性子',
    'You have': '你有',
    'Your total playtime is': '你的累计游戏时长是',
    'Zombie': '僵尸',
    'Sonic': '音速',
    'Logs': '木头',
    'Next at': '下一个在',
    'Locks': '锁',
    'Joints': '接头',
    '×2 to all dimensions': 'x2 给所有维度',
    'Photonic Wall': '光子墙',
    'In the': '打卡',
    'Master': '精通',
    'more at': ' 在',
    'XP': '经验',
    'String Theorist': '弦理论家',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Added Legendary Heroes that represent the best of the best.\n- Removed version tracker since it is no longer useful.': '添加了代表最好的传奇英雄。\n-删除版本跟踪器，因为它不再有用。',
    'Infinity no longer resets Heroes.\n- Added Actions that produce XP.': '无限不再重置英雄。\n-添加了产生经验的动作。',
    'Added an Infinity prestige layer that allows you to purchase new powerful upgrades.\n- Added an autobuyer for Lich Galaxies.': '添加了无限声望层，可让您购买新的强大升级。\n-为巫妖星系添加了自动购买器。',
    'Automation no longer resets on version update.\n- Added an autobuyer for Dimensional Boosts.': '自动化不再在版本更新时重置。\n-为维度提升添加了自动购买程序。',
    'Heroes automatically level up without spending any XP.\n- You can now lock certain Actions to keep them between refreshes.': '英雄无需花费任何经验值即可自动升级。\n-您现在可以锁定某些动作，以使其在刷新之间保持不变。',
    'Added Actions that can provide positive or negative boosts when launched.\n- Common Heroes now also automatically unlock corresponding Dimension automation.': '添加了可以在启动时提供正面或负面提升的动作。\n- 普通英雄现在还可以自动解锁相应的维度自动化。',
    'Added rare Heroes that provide even better boosts.\n- Renamed lootboxes to toolboxes.': '添加了稀有的英雄，它们甚至可以提供更好的提升。\n-将战利品箱重命名为工具箱。',
    'Your Mete Points now give you more XP per milestone based on their amount.\n- Added an option to disable lootbox opening window.': '您的元点数现在可以根据里程碑的数量为您提供更多经验。\n-添加了一个选项，用于禁用战利品打开窗口。',
    'You can now reset all your Dimension stuff to obtain Galaxies that boost Tickspeed Upgrade power.\n- Added an autobuyer for Dimensional Shifts.': '现在，您可以重置所有维度的东西，以获得增强Tick速度升级功能的星系。\n-为维度偏移添加了自动购买器。',
    'Added uncommon Heroes that boost dimension power indirectly.\n- The ads did not work, so they are scrapped. You do not need to watch an ad to get free XP, but the amount is reduced from 5 to 1.': '添加了不常见的英雄，这些英雄可以间接提高维度能力。\n-广告没有效果，因此被废弃了。 您无需观看广告即可获得免费的经验值，但数量会从5减少到1.1',
    'You can watch an advertisement to get 5 XP.\n- Matter Dimension and Tickspeed Upgrade costs are softcapped.': '您可以观看广告获得5 经验。\n -无内容维度和“Tick速度”升级费用没有上限。',
    'Everything is 20% better with blob emojis': '使用Blob表情符号，一切都会好20％',
    'Reset for': '重置',
    'Nothing can escape the gravity of a black hole, except the dedication of incremental gamers': '除了增量游戏玩家的奉献精神，任何事情都无法逃脱黑洞的引力',
    'This is not a TPT mod. On the other hand, you might find yourself enjoying TPT mods. TPT stands for The Prestige Tree, check it out': '这不是TPT mod。 另一方面，您可能会发现自己喜欢TPT mod。 TPT代表声望树，请查看',
    'Elite': '精品',
    'Added newsticker to the top of the page.\n- Added an ability to sacrifice all your Master Dimensions except 10th and get a boost to 10th Master Dimension.': '在页面顶部添加新贴纸。增加了一个能力牺牲你所有的精通维度，除了第10次，并得到一个提升到第10次精通维度。',
    'Introduced Tickspeed Upgrades.\n- Removed \"Get a Rankless Point\" button, due to being not needed.': '引入了Tick速度升级。\n-由于不需要，已删除“获取无等级点数”按钮。',
    'This newsticker is softca': '这个新贴纸是软的',
    'Refreshes in': '刷新于',
    'Please wait, we are loading the advertisement...': '请稍候，我们正在加载广告...',
    'Please accept 5 XP for your wait!': '请接受5倍经验，因为您的期待！',
    'Paste your save string into the box below': '将您的存档字符串粘贴到下面的框中',
    'Gain': '收益',
    'Added Heroes that boost Mester Dimensions. You can get them from lootboxes, bought with XP. Gain 1 XP for each power of 10 reached in Mester Points.\n- Added an ability to change notations, if you want to return to this April Fools prank.': '增加了可以提高掌握维度的英雄。 您可以从用经验购买的战利品箱中获得它们。 每获得10点乘以掌握点所获得的力量，则获得1点经验值。\n-如果您想返回到愚人节恶作剧，添加了一种更改符号的功能。',
    'Added automation for Rankled Dimensions.\n- First two Rankled Dimensions now work 2x faster.': '增加了对“分级维度”的自动化。\n-现在，前两个“分级维度”的工作速度提高了2倍。',
    'Rankled': '发炎',
    'Rankless': '无等级',
    'Rankles': '溃烂',
    'Do you wish to return to the Darkness Age?': '您想回到黑暗时代吗？',
    'Each level gives +100% to all': '每级给所有 +100％',
    'Each level gives +10% Heroes in': '每个等级提供+10％英雄',
    'Ask for your blessing from Hevipelle today!': '今天就向Hevipelle祈求您的祝福！',
    '\"Escape from Vantablack\" has better newstickers': '“逃离万塔布莱克”具有更好的新标贴',
    'You can find much more stuff like this on r/incremental_games subreddit': '您可以在r / incremental_games subreddit上找到更多类似的内容',
    'You can now buy max Tickspeed Upgrades.\n- Added version tracker.': '您现在可以购买最大的Tick速度升级。\n-添加了版本跟踪器。',
    'You won The Game!': '您赢了游戏！',
    'Rankness': '等级',
    'You start with 10 Rankness Points.\n- 1st Rankness Dimension now works 2x faster.': '您从10个等级点开始。\n-第一个等级维度现在的运行速度提高了2倍。',
    'Lootbox': '战利品箱',
    'Mester': '掌握',
    'Matter Dimensions': '物质维度',
    'All numbers are now presented in a clear and concise modern format.\n- April Fools!': '现在，所有数字均以简洁明了的现代格式显示。\n-愚人节！',
    'Get a': '获取1',
    'Dimension is more powerful based on unspent Infinity Points': '基于未花费的无限点，维度更强大',
    'Darkness': '黑暗',
    'Dankness': '潮湿',
    'Buying a Dankness Dimension now provides a 2x boost to itself.\n- Added a link to my other game, Matter Dimensions.': '现在，购买潮湿维度可以使自身提高2倍。\n-为我的其他游戏物质维度添加了一个链接。',
    'If you can time travel, click on newsticker before this one': '如果您可以抽空旅行，请在此之前单击新闻速递',
    'Dimensions production (additive': '维度生产（附加',
    'Dimension Boosts and': '维度提升和',
    'Can you collect all Heroes?': '你可以收集所有英雄吗？',
    'Dimensional Sacrifice ×': '维度牺牲×',
    'Dimensional Sacrifice resets nothing, and Sacrifice once per tick': '维度牺牲不会重置任何值，每Tick牺牲一次',
    'Anybody wants to go meta?': '有人想达到元吗？',
    'Yep, this game was totally copied from Antimatter Dimensions': '是的，这个游戏完全是从反物质维度复制来的',
    'Newsticker confirmed': '新闻速递确认',
    'Nukes': '核武器',
    'opening window': '开窗',
    'Rare': '稀有',
    'Screws': '螺丝钉',
    'Snail': '蜗牛',
    'Rester': '停留',
    'Automation is cheaper.\n- The first three Rester Dimensions now work 2x faster.': '自动化的价格更低。\n-现在，前三个停留维度的运行速度提高了2倍。',
    '2% to Tickspeed Upgrade power': '2％至Ticks速度升级功率',
    'to': ' 为',
    'Rented': '租用',
    'Renamed': '重命名',
    'Rested': '休息',
    'Each Tickspeed Upgrade increases tickspeed by': '每次Tick速度升级将Tick速度提高了',
    'Galaxies do not reset other Dimension stuff': '星系不会重设其他维度的东西',
    'Legendary': '传奇',
    'Dimension Shift': '维度偏移',
    'Dimension Boost': '维度提升',
    'Congratulations! You have beaten the game!': '恭喜你！ 您已经击败了游戏！',
    'Actions are better': '操作更好了',
    'Hard Reset': '硬重置',
    'Extreme Dimensional Boost scaling starts 10 Boosts later': '极限维度提升的缩放将在10次提升之后开始',
    'Galaxies do not reset Dimension Boosts': '星系不会重置维度提升',
    'Here is your save string': '这是你的存档字符串',
    'Only Final Toolbox is left, with the cost scaling with the current XP': '只剩下最后的工具箱，成本随着当前经验的增加而增加',
    'You start with 6 Dimension Shifts': '你从第 6 维度偏移开始',
    'Watch an ad to get 5 XP': '观看广告获得5倍经验',
    'You can continue playing, if you want.': '如果你愿意，可以继续玩。',
    'Uncommon': '罕见',
    'Update to the version': '更新到版本',
    'Silver Surfer': '银色冲浪者',
    'Sorry, we were unable to load an advertisement.': '抱歉，我们无法加载广告。',
    'Subscribe to SuperSpruce': '',
    'The first Tickspeed upgrade now costs 10x less.\n- You can perform Dimension Boosts after you reached max Rested Dimensions, each for increased cost.': '现在，第一次Tickspeed升级的价格降低了10倍。\n-您可以在达到最大“静止维度”后执行“维度提升”，每一次都会增加成本。',
    'This action is irreversible!': '这个动作是不可逆的！',
    'This newsticker was specifically made unreasonably long to create an impression that there is much more meaning in it than seems at the first glance. There isn\'t.': '专门为使此新贴纸过长而造成的印象是，它的含义比乍看之下要多得多。 没有。',
    'Unlock an additional dimension': '解锁其他维度',
    'Get an additional Lock': '得到一个额外的锁',
    'Check my other game,': '查看我的其他游戏，',
    'Are you sure you want to perform a Hard Reset?': '您确定要执行硬重置吗？',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Current:": "当前:",
    "Boosts ": "提升 ",
    "Dimensions: ": "维度: ",
    "Heroes: ": "英雄: ",
    "Version": "版本",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    " Locked": " 未解锁",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^([\d\.]+)e([\d\.,]+)$/,
//    /^([\d\.]+) 🎈$/,
//    /^([\d\.]+) 🎲$/,
//    /^([\d\.]+) ⛲$/,
//    /^([\d\.]+) 📧$/,
//    /^([\d\.]+) 🃏$/,
//    /^([\d\.]+) 🖱$/,
//    /^([\d\.]+) 🏰$/,
//    /^([\d\.]+) ⏳$/,
//    /^([\d\.]+) 🧊$/,
//    /^([\d\.]+) 🌍$/,
//    /^([\d\.]+) ☂$/,
//    /^([\d\.]+) 🧅$/,
//    /^([\d\.]+) 🧳$/,
//    /^([\d\.]+) ⌨$/,
//    /^([\d\.]+) ⌨$/,
//    /^([\d\.]+) 😐$/,
//    /^([\d\.]+) ❄$/,
//    /^([\d\.]+) 🚦$/,
//    /^([\d\.]+) 🌈$/,
//    /^([\d\.]+) 🪂$/,
//    /^([\d\.]+) 💤$/,
//    /^([\d\.]+) ❌$/,
//    /^([\d\.]+) 🚑🧊$/,
//    /^([\d\.]+) 🚑⏳$/,
//    /^([\d\.]+) 🚑🃏$/,
//    /^([\d\.]+) 🚑⛲$/,
//    /^([\d\.]+) 🚑☂$/,
//    /^([\d\.]+) 🚑🚑$/,
//    /^([\d\.]+) 🚑🧳$/,
//    /^([\d\.]+) 🚑❌$/,
//    /^([\d\.]+) 🎈🎲$/,
    /^([\d\.]+) (.+)$/,
    /^([\d\.,]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Spend (\d+) Rocks for (\d+) Logs$/, '花费 $1 石头获得 $2 木头'],
    [/^Spend (\d+) Rocks for (\d+) Bars$/, '花费 $1 石头获得 $2 金属条'],
    [/^Spend (\d+) Rocks for (\d+) HP$/, '花费 $1 石头获得 $2 生命值'],
    [/^Spend (\d+) Rocks for (\d+) DP$/, '花费 $1 石头获得 $2 DP'],
    [/^Spend (\d+) Rocks and (\d+) Logs for (\d+) Bars$/, '花费 $1 石头和 $2 木头 获得 $3 金属条'],
    [/^Spend (\d+) Logs for (\d+) DP$/, '花费 $1 木头获得 $2 DP'],
    [/^Spend (\d+) Logs for (\d+) Bars$/, '花费 $1 木头获得 $2 金属条'],
    [/^Spend (\d+) Bars for (\d+) HP$/, '花费 $1 金属条获得 $2 生命值'],
    [/^Spend (\d+) Bars for (\d+) DP$/, '花费 $1 金属条获得 $2 DP'],
    [/^Cost: (.+) Bars$/, '成本: $1 金属条'],
    [/^Cost: (.+) Logs$/, '成本: $1 木头'],
    [/^Get (.+) Rocks$/, '获得 $1 石头'],
    [/^Get (.+) Logs$/, '获得 $1 木头'],
    [/^Get (.+) Bars$/, '获得 $1 金属条'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);